# Generated by Django 5.0.4 on 2024-05-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_influxuserdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodereduserdata',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mqttmetadata',
            name='user_topic_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
