# Generated by Django 5.0.4 on 2024-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttmetadata',
            name='user_topic_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='nodereduserdata',
            name='access_token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nodereduserdata',
            name='container_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
