# Generated by Django 5.0.4 on 2024-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_nodereduserdata_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodereduserdata',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nodereduserdata',
            name='username',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
