# Generated by Django 5.2 on 2025-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_nodereduserdata_password_nodereduserdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttmetadata',
            name='inout_role_name',
            field=models.CharField(default='null', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mqttmetadata',
            name='device_role_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mqttmetadata',
            name='nodered_role_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
