# Generated by Django 4.2.5 on 2024-01-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nodereduserdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodereduserdata',
            old_name='node_red_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='nodereduserdata',
            old_name='nodered_container_name',
            new_name='container_name',
        ),
        migrations.RemoveField(
            model_name='nodereduserdata',
            name='id',
        ),
        migrations.AddField(
            model_name='nodereduserdata',
            name='container_port',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='nodereduserdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
