# Generated by Django 4.2.5 on 2023-10-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
